{{- if ne (default "managed" (dig "mecatl" "mode" "managed" (default dict .Values.global))) "external" }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mecabroker.fullname" . }}
  labels: {{- include "mecabroker.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
