{{- if ne (default "managed" (dig "mecatl" "mode" "managed" (default dict .Values.global))) "external" }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mecabroker.fullname" . }}
  labels: {{- include "mecabroker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "mecabroker.labels" . | nindent 4 }}
  ports:
    - {name: public, port: {{ .Values.service.port }}, targetPort: public}
{{- end }}
